#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Tsms.Resource", IsApplication=true)]

namespace Tsms
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int splash_screen = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int SplashScreen = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060003
			public const int cancel_applog_button = 2131099651;
			
			// aapt resource value: 0x7f060013
			public const int cancel_config_button = 2131099667;
			
			// aapt resource value: 0x7f060016
			public const int cancel_contact_button = 2131099670;
			
			// aapt resource value: 0x7f060002
			public const int clear_applog_button = 2131099650;
			
			// aapt resource value: 0x7f060014
			public const int contact_text = 2131099668;
			
			// aapt resource value: 0x7f060009
			public const int edit_smsconfig_button = 2131099657;
			
			// aapt resource value: 0x7f060008
			public const int edit_smscontact_button = 2131099656;
			
			// aapt resource value: 0x7f060000
			public const int layout_logtop = 2131099648;
			
			// aapt resource value: 0x7f060012
			public const int save_config_button = 2131099666;
			
			// aapt resource value: 0x7f060015
			public const int save_contact_button = 2131099669;
			
			// aapt resource value: 0x7f06000b
			public const int smsreadbotton = 2131099659;
			
			// aapt resource value: 0x7f060006
			public const int start_service_button = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int stop_service_button = 2131099655;
			
			// aapt resource value: 0x7f060001
			public const int text_applog = 2131099649;
			
			// aapt resource value: 0x7f060011
			public const int text_controlphone = 2131099665;
			
			// aapt resource value: 0x7f060005
			public const int text_sendfailurestatistics = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int text_sendsuccessstatistics = 2131099652;
			
			// aapt resource value: 0x7f06000f
			public const int text_smtpaccount = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int text_smtppassword = 2131099664;
			
			// aapt resource value: 0x7f06000e
			public const int text_smtpport = 2131099662;
			
			// aapt resource value: 0x7f06000d
			public const int text_smtpserver = 2131099661;
			
			// aapt resource value: 0x7f06000c
			public const int text_template = 2131099660;
			
			// aapt resource value: 0x7f06000a
			public const int view_applog_button = 2131099658;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AppLogLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int SMSContentProviderView = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int SMSTransferConfigLayout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int SMSTransferContactLayout = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] TitleAttr;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
